export const BCMS_USER_ID = 'BCMS_USER_ID';
export const BCMS_AUTH_TOKEN = 'BCMS_AUTH_TOKEN';
export const BCMS_USER_EMPLOYEE_ID = 'BCMS_USER_EMPLOYEE_ID';
export const BCMS_USER_ACCESS = 'BCMS_USER_ACCESS';